"""Init

Revision ID: 9e6979879237
Revises: 
Create Date: 2023-10-11 16:35:37.503785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6979879237'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Название категории', sa.String(length=225), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Название категории')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Вопрос из викторины', sa.String(length=525), nullable=False),
    sa.Column('Ответ на вопрос', sa.String(length=125), nullable=False),
    sa.Column('Дата создания', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('Номер записи на сайта', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Вопрос из викторины'),
    sa.UniqueConstraint('Номер записи на сайта')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
